### ISSUE TITLE
Pod update?

### ISSUE THREAD

**Issue by F1NaL** [Darktt/DTAlertView#16]
Thx for awesome AlertView.
Can you update pod ?

**Comment by Darktt** [comment]
Submit to CocoaPods/Specs waiting merge.

**Comment by Darktt** [comment]
Was merged to CocoaPods/Specs.

**Comment by F1NaL** [comment]
Big Thx!

**Comment by UXDart** [comment]
in cocoapods.org there is the version 1.2.1, can you update to 1.4.1? thanks

**Comment by Darktt** [comment]
Update 1.4.2 to CocoaPods (Validating)

**Comment by UXDart** [comment]
Thanks! :)
