### ISSUE TITLE
disable/non response from ViewController

### ISSUE THREAD

**Issue by UXDart** [Darktt/DTAlertView#19]
Hello
I'm showing a DTAlertView with just a message and a Cancel button, if I cancel, the alertview dismisses, but then the viewcontroller doesn't responds to anything. any idea what it could be?

TIA

**Comment by UXDart** [comment]
I thought it stops happening, but not, is something that happens sometimes... I couldn't find a pattern. any idea?

**Comment by Darktt** [comment]
Can you monitoring -setHidden: behavior in DTAlertView.m line 172 (version 1.4.2).
I guess those key window are not switch correctly.

**Comment by UXDart** [comment]
Thanks
It is calling setHidden, and I can see that _previousKeyWindow is the type `UIAlertControllerShimPresenterWindow` so I assume is the wrong window... (?)

TIA

**Comment by UXDart** [comment]
I just changed the code to this, and it seems to work, but I'm not sure what happens in all cases, like if there is a keyboard:

```
    UIWindow *topWindow = [[[UIApplication sharedApplication].windows sortedArrayUsingComparator:^NSComparisonResult(UIWindow *win1, UIWindow *win2) {
        return [@(win1.windowLevel) compare:@(win2.windowLevel)];
    }] lastObject];
    _previousKeyWindow = topWindow;// DTRetain([[UIApplication sharedApplication] keyWindow]);
```

what do you think?

**Comment by Darktt** [comment]
I guess you use UIAlertController before DTAlertView,
maybe UIAlertController after dismiss that window not removed,
so DTAlertView get wrong key window,
and that after dismiss exchange to wrong key window.

**Comment by UXDart** [comment]
yes, that was the problem. thanks!
